namespace BookApi.WinForms;

partial class Form1
{
    private System.ComponentModel.IContainer components = null;
    private SplitContainer splitMain = null!;
    private GroupBox grpSearch = null!;
    private Label lblKeyword = null!;
    private TextBox txtKeyword = null!;
    private Label lblSearchCategory = null!;
    private ComboBox cboSearchCategory = null!;
    private Button btnSearch = null!;
    private Button btnRefresh = null!;
    private DataGridView dgvBooks = null!;
    private GroupBox grpDetails = null!;
    private Label lblBookId = null!;
    private TextBox txtBookId = null!;
    private Label lblTitle = null!;
    private TextBox txtTitle = null!;
    private Label lblAuthor = null!;
    private TextBox txtAuthor = null!;
    private Label lblCategory = null!;
    private ComboBox cboCategory = null!;
    private Label lblPrice = null!;
    private NumericUpDown nudPrice = null!;
    private Label lblQuantity = null!;
    private NumericUpDown nudQuantity = null!;
    private Label lblDescription = null!;
    private TextBox txtDescription = null!;
    private Label lblImage = null!;
    private TextBox txtImagePath = null!;
    private Button btnChooseImage = null!;
    private PictureBox picBook = null!;
    private Button btnAdd = null!;
    private Button btnUpdate = null!;
    private Button btnDelete = null!;
    private Button btnClear = null!;
    private DataGridViewTextBoxColumn colBookId = null!;
    private DataGridViewTextBoxColumn colTitle = null!;
    private DataGridViewTextBoxColumn colAuthor = null!;
    private DataGridViewTextBoxColumn colCategory = null!;
    private DataGridViewTextBoxColumn colPrice = null!;
    private DataGridViewTextBoxColumn colQuantity = null!;

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        splitMain = new SplitContainer();
        grpSearch = new GroupBox();
        lblKeyword = new Label();
        txtKeyword = new TextBox();
        lblSearchCategory = new Label();
        cboSearchCategory = new ComboBox();
        btnSearch = new Button();
        btnRefresh = new Button();
        dgvBooks = new DataGridView();
        colBookId = new DataGridViewTextBoxColumn();
        colTitle = new DataGridViewTextBoxColumn();
        colAuthor = new DataGridViewTextBoxColumn();
        colCategory = new DataGridViewTextBoxColumn();
        colPrice = new DataGridViewTextBoxColumn();
        colQuantity = new DataGridViewTextBoxColumn();
        grpDetails = new GroupBox();
        lblBookId = new Label();
        txtBookId = new TextBox();
        lblTitle = new Label();
        txtTitle = new TextBox();
        lblAuthor = new Label();
        txtAuthor = new TextBox();
        lblCategory = new Label();
        cboCategory = new ComboBox();
        lblPrice = new Label();
        nudPrice = new NumericUpDown();
        lblQuantity = new Label();
        nudQuantity = new NumericUpDown();
        lblDescription = new Label();
        txtDescription = new TextBox();
        lblImage = new Label();
        txtImagePath = new TextBox();
        btnChooseImage = new Button();
        picBook = new PictureBox();
        btnAdd = new Button();
        btnUpdate = new Button();
        btnDelete = new Button();
        btnClear = new Button();
        ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
        splitMain.Panel1.SuspendLayout();
        splitMain.Panel2.SuspendLayout();
        splitMain.SuspendLayout();
        grpSearch.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvBooks).BeginInit();
        grpDetails.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)nudPrice).BeginInit();
        ((System.ComponentModel.ISupportInitialize)nudQuantity).BeginInit();
        ((System.ComponentModel.ISupportInitialize)picBook).BeginInit();
        SuspendLayout();
        splitMain.Dock = DockStyle.Fill;
        splitMain.Location = new Point(0, 0);
        splitMain.Name = "splitMain";
        splitMain.Panel1.Controls.Add(dgvBooks);
        splitMain.Panel1.Controls.Add(grpSearch);
        splitMain.Panel2.Controls.Add(grpDetails);
        splitMain.Size = new Size(1360, 760);
        splitMain.SplitterDistance = 760;
        splitMain.TabIndex = 0;
        grpSearch.Controls.Add(btnRefresh);
        grpSearch.Controls.Add(btnSearch);
        grpSearch.Controls.Add(cboSearchCategory);
        grpSearch.Controls.Add(lblSearchCategory);
        grpSearch.Controls.Add(txtKeyword);
        grpSearch.Controls.Add(lblKeyword);
        grpSearch.Dock = DockStyle.Top;
        grpSearch.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        grpSearch.Location = new Point(0, 0);
        grpSearch.Name = "grpSearch";
        grpSearch.Size = new Size(760, 118);
        grpSearch.TabIndex = 0;
        grpSearch.TabStop = false;
        grpSearch.Text = "Search Books";
        lblKeyword.AutoSize = true;
        lblKeyword.Font = new Font("Segoe UI", 9F);
        lblKeyword.Location = new Point(24, 34);
        lblKeyword.Name = "lblKeyword";
        lblKeyword.Size = new Size(60, 15);
        lblKeyword.TabIndex = 0;
        lblKeyword.Text = "Keyword:";
        txtKeyword.Font = new Font("Segoe UI", 9.5F);
        txtKeyword.Location = new Point(118, 30);
        txtKeyword.Name = "txtKeyword";
        txtKeyword.PlaceholderText = "Search by title, author, category...";
        txtKeyword.Size = new Size(334, 24);
        txtKeyword.TabIndex = 1;
        lblSearchCategory.AutoSize = true;
        lblSearchCategory.Font = new Font("Segoe UI", 9F);
        lblSearchCategory.Location = new Point(24, 73);
        lblSearchCategory.Name = "lblSearchCategory";
        lblSearchCategory.Size = new Size(58, 15);
        lblSearchCategory.TabIndex = 2;
        lblSearchCategory.Text = "Category:";
        cboSearchCategory.DropDownStyle = ComboBoxStyle.DropDownList;
        cboSearchCategory.Font = new Font("Segoe UI", 9.5F);
        cboSearchCategory.FormattingEnabled = true;
        cboSearchCategory.Location = new Point(118, 69);
        cboSearchCategory.Name = "cboSearchCategory";
        cboSearchCategory.Size = new Size(334, 25);
        cboSearchCategory.TabIndex = 3;
        btnSearch.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        btnSearch.Location = new Point(495, 28);
        btnSearch.Name = "btnSearch";
        btnSearch.Size = new Size(112, 30);
        btnSearch.TabIndex = 4;
        btnSearch.Text = "Search";
        btnSearch.UseVisualStyleBackColor = true;
        btnRefresh.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        btnRefresh.Location = new Point(625, 28);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Size = new Size(112, 30);
        btnRefresh.TabIndex = 5;
        btnRefresh.Text = "Refresh";
        btnRefresh.UseVisualStyleBackColor = true;
        dgvBooks.AllowUserToAddRows = false;
        dgvBooks.AllowUserToDeleteRows = false;
        dgvBooks.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        dgvBooks.BackgroundColor = Color.White;
        dgvBooks.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvBooks.Columns.AddRange(new DataGridViewColumn[] { colBookId, colTitle, colAuthor, colCategory, colPrice, colQuantity });
        dgvBooks.Dock = DockStyle.Fill;
        dgvBooks.Location = new Point(0, 118);
        dgvBooks.MultiSelect = false;
        dgvBooks.Name = "dgvBooks";
        dgvBooks.ReadOnly = true;
        dgvBooks.RowHeadersVisible = false;
        dgvBooks.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvBooks.Size = new Size(760, 642);
        dgvBooks.TabIndex = 1;
        colBookId.DataPropertyName = "BookId";
        colBookId.FillWeight = 65F;
        colBookId.HeaderText = "ID";
        colBookId.Name = "colBookId";
        colBookId.ReadOnly = true;
        colTitle.DataPropertyName = "Title";
        colTitle.FillWeight = 180F;
        colTitle.HeaderText = "Title";
        colTitle.Name = "colTitle";
        colTitle.ReadOnly = true;
        colAuthor.DataPropertyName = "Author";
        colAuthor.FillWeight = 140F;
        colAuthor.HeaderText = "Author";
        colAuthor.Name = "colAuthor";
        colAuthor.ReadOnly = true;
        colCategory.DataPropertyName = "CategoryName";
        colCategory.FillWeight = 120F;
        colCategory.HeaderText = "Category";
        colCategory.Name = "colCategory";
        colCategory.ReadOnly = true;
        colPrice.DataPropertyName = "Price";
        colPrice.FillWeight = 90F;
        colPrice.HeaderText = "Price";
        colPrice.Name = "colPrice";
        colPrice.ReadOnly = true;
        colQuantity.DataPropertyName = "Quantity";
        colQuantity.FillWeight = 85F;
        colQuantity.HeaderText = "Qty";
        colQuantity.Name = "colQuantity";
        colQuantity.ReadOnly = true;
        grpDetails.Controls.Add(btnClear);
        grpDetails.Controls.Add(btnDelete);
        grpDetails.Controls.Add(btnUpdate);
        grpDetails.Controls.Add(btnAdd);
        grpDetails.Controls.Add(picBook);
        grpDetails.Controls.Add(btnChooseImage);
        grpDetails.Controls.Add(txtImagePath);
        grpDetails.Controls.Add(lblImage);
        grpDetails.Controls.Add(txtDescription);
        grpDetails.Controls.Add(lblDescription);
        grpDetails.Controls.Add(nudQuantity);
        grpDetails.Controls.Add(lblQuantity);
        grpDetails.Controls.Add(nudPrice);
        grpDetails.Controls.Add(lblPrice);
        grpDetails.Controls.Add(cboCategory);
        grpDetails.Controls.Add(lblCategory);
        grpDetails.Controls.Add(txtAuthor);
        grpDetails.Controls.Add(lblAuthor);
        grpDetails.Controls.Add(txtTitle);
        grpDetails.Controls.Add(lblTitle);
        grpDetails.Controls.Add(txtBookId);
        grpDetails.Controls.Add(lblBookId);
        grpDetails.Dock = DockStyle.Fill;
        grpDetails.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
        grpDetails.Location = new Point(0, 0);
        grpDetails.Name = "grpDetails";
        grpDetails.Size = new Size(596, 760);
        grpDetails.TabIndex = 0;
        grpDetails.TabStop = false;
        grpDetails.Text = "Book Details";
        lblBookId.AutoSize = true;
        lblBookId.Font = new Font("Segoe UI", 9F);
        lblBookId.Location = new Point(28, 41);
        lblBookId.Name = "lblBookId";
        lblBookId.Size = new Size(49, 15);
        lblBookId.TabIndex = 0;
        lblBookId.Text = "Book ID:";
        txtBookId.Font = new Font("Segoe UI", 9.5F);
        txtBookId.Location = new Point(142, 37);
        txtBookId.Name = "txtBookId";
        txtBookId.ReadOnly = true;
        txtBookId.Size = new Size(164, 24);
        txtBookId.TabIndex = 1;
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("Segoe UI", 9F);
        lblTitle.Location = new Point(28, 80);
        lblTitle.Name = "lblTitle";
        lblTitle.Size = new Size(33, 15);
        lblTitle.TabIndex = 2;
        lblTitle.Text = "Title:";
        txtTitle.Font = new Font("Segoe UI", 9.5F);
        txtTitle.Location = new Point(142, 76);
        txtTitle.Name = "txtTitle";
        txtTitle.Size = new Size(418, 24);
        txtTitle.TabIndex = 3;
        lblAuthor.AutoSize = true;
        lblAuthor.Font = new Font("Segoe UI", 9F);
        lblAuthor.Location = new Point(28, 119);
        lblAuthor.Name = "lblAuthor";
        lblAuthor.Size = new Size(47, 15);
        lblAuthor.TabIndex = 4;
        lblAuthor.Text = "Author:";
        txtAuthor.Font = new Font("Segoe UI", 9.5F);
        txtAuthor.Location = new Point(142, 115);
        txtAuthor.Name = "txtAuthor";
        txtAuthor.Size = new Size(418, 24);
        txtAuthor.TabIndex = 5;
        lblCategory.AutoSize = true;
        lblCategory.Font = new Font("Segoe UI", 9F);
        lblCategory.Location = new Point(28, 158);
        lblCategory.Name = "lblCategory";
        lblCategory.Size = new Size(58, 15);
        lblCategory.TabIndex = 6;
        lblCategory.Text = "Category:";
        cboCategory.DropDownStyle = ComboBoxStyle.DropDownList;
        cboCategory.Font = new Font("Segoe UI", 9.5F);
        cboCategory.FormattingEnabled = true;
        cboCategory.Location = new Point(142, 154);
        cboCategory.Name = "cboCategory";
        cboCategory.Size = new Size(418, 25);
        cboCategory.TabIndex = 7;
        lblPrice.AutoSize = true;
        lblPrice.Font = new Font("Segoe UI", 9F);
        lblPrice.Location = new Point(28, 198);
        lblPrice.Name = "lblPrice";
        lblPrice.Size = new Size(36, 15);
        lblPrice.TabIndex = 8;
        lblPrice.Text = "Price:";
        nudPrice.DecimalPlaces = 2;
        nudPrice.Font = new Font("Segoe UI", 9.5F);
        nudPrice.Location = new Point(142, 194);
        nudPrice.Maximum = new decimal(new int[] { 1000000, 0, 0, 0 });
        nudPrice.Name = "nudPrice";
        nudPrice.Size = new Size(164, 24);
        nudPrice.TabIndex = 9;
        lblQuantity.AutoSize = true;
        lblQuantity.Font = new Font("Segoe UI", 9F);
        lblQuantity.Location = new Point(332, 198);
        lblQuantity.Name = "lblQuantity";
        lblQuantity.Size = new Size(56, 15);
        lblQuantity.TabIndex = 10;
        lblQuantity.Text = "Quantity:";
        nudQuantity.Font = new Font("Segoe UI", 9.5F);
        nudQuantity.Location = new Point(418, 194);
        nudQuantity.Maximum = new decimal(new int[] { 100000, 0, 0, 0 });
        nudQuantity.Name = "nudQuantity";
        nudQuantity.Size = new Size(142, 24);
        nudQuantity.TabIndex = 11;
        lblDescription.AutoSize = true;
        lblDescription.Font = new Font("Segoe UI", 9F);
        lblDescription.Location = new Point(28, 239);
        lblDescription.Name = "lblDescription";
        lblDescription.Size = new Size(70, 15);
        lblDescription.TabIndex = 12;
        lblDescription.Text = "Description:";
        txtDescription.Font = new Font("Segoe UI", 9.5F);
        txtDescription.Location = new Point(142, 235);
        txtDescription.Multiline = true;
        txtDescription.Name = "txtDescription";
        txtDescription.ScrollBars = ScrollBars.Vertical;
        txtDescription.Size = new Size(418, 112);
        txtDescription.TabIndex = 13;
        lblImage.AutoSize = true;
        lblImage.Font = new Font("Segoe UI", 9F);
        lblImage.Location = new Point(28, 369);
        lblImage.Name = "lblImage";
        lblImage.Size = new Size(40, 15);
        lblImage.TabIndex = 14;
        lblImage.Text = "Image:";
        txtImagePath.Font = new Font("Segoe UI", 9.5F);
        txtImagePath.Location = new Point(142, 365);
        txtImagePath.Name = "txtImagePath";
        txtImagePath.ReadOnly = true;
        txtImagePath.Size = new Size(300, 24);
        txtImagePath.TabIndex = 15;
        btnChooseImage.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        btnChooseImage.Location = new Point(460, 362);
        btnChooseImage.Name = "btnChooseImage";
        btnChooseImage.Size = new Size(100, 30);
        btnChooseImage.TabIndex = 16;
        btnChooseImage.Text = "Choose";
        btnChooseImage.UseVisualStyleBackColor = true;
        picBook.BackColor = Color.WhiteSmoke;
        picBook.BorderStyle = BorderStyle.FixedSingle;
        picBook.Location = new Point(142, 409);
        picBook.Name = "picBook";
        picBook.Size = new Size(220, 220);
        picBook.SizeMode = PictureBoxSizeMode.Zoom;
        picBook.TabIndex = 17;
        picBook.TabStop = false;
        btnAdd.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        btnAdd.Location = new Point(31, 671);
        btnAdd.Name = "btnAdd";
        btnAdd.Size = new Size(120, 38);
        btnAdd.TabIndex = 18;
        btnAdd.Text = "Add";
        btnAdd.UseVisualStyleBackColor = true;
        btnUpdate.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        btnUpdate.Location = new Point(171, 671);
        btnUpdate.Name = "btnUpdate";
        btnUpdate.Size = new Size(120, 38);
        btnUpdate.TabIndex = 19;
        btnUpdate.Text = "Update";
        btnUpdate.UseVisualStyleBackColor = true;
        btnDelete.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        btnDelete.Location = new Point(311, 671);
        btnDelete.Name = "btnDelete";
        btnDelete.Size = new Size(120, 38);
        btnDelete.TabIndex = 20;
        btnDelete.Text = "Delete";
        btnDelete.UseVisualStyleBackColor = true;
        btnClear.Font = new Font("Segoe UI", 9.5F, FontStyle.Bold);
        btnClear.Location = new Point(440, 671);
        btnClear.Name = "btnClear";
        btnClear.Size = new Size(120, 38);
        btnClear.TabIndex = 21;
        btnClear.Text = "Clear";
        btnClear.UseVisualStyleBackColor = true;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1360, 760);
        Controls.Add(splitMain);
        MinimumSize = new Size(1300, 720);
        Name = "Form1";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "Book Management - Web API";
        splitMain.Panel1.ResumeLayout(false);
        splitMain.Panel2.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
        splitMain.ResumeLayout(false);
        grpSearch.ResumeLayout(false);
        grpSearch.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)dgvBooks).EndInit();
        grpDetails.ResumeLayout(false);
        grpDetails.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudPrice).EndInit();
        ((System.ComponentModel.ISupportInitialize)nudQuantity).EndInit();
        ((System.ComponentModel.ISupportInitialize)picBook).EndInit();
        ResumeLayout(false);
    }
}
